apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yhwy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-yhwy@sha256:21ca996113ae1566659ea2e708c21afdab4ae1d1b877ea99da7e5203d707a4ab
        name: my-nodejs
        resources: {}
status: {}
